/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class site_luoyu_jni_JniHello */

#ifndef _Included_site_luoyu_jni_JniHello
#define _Included_site_luoyu_jni_JniHello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     site_luoyu_jni_JniHello
 * Method:    SayHellow
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_site_luoyu_jni_JniHello_SayHellow
  (JNIEnv *, jobject, jint);

/*
 * Class:     site_luoyu_jni_JniHello
 * Method:    tellName
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_site_luoyu_jni_JniHello_tellName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     site_luoyu_jni_JniHello
 * Method:    getBytes
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_site_luoyu_jni_JniHello_getBytes
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     site_luoyu_jni_JniHello
 * Method:    setField
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_site_luoyu_jni_JniHello_setField
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
